// ─────────────────────────────────────────────────────────────────────────────
// Demo / seed data — used when Supabase is not configured ("demo mode")
// Also used as the source for the SQL seed file.
// ─────────────────────────────────────────────────────────────────────────────

import type { Category, Model, Prompt, Profile } from "@/types/database";

export const demoCategories: Category[] = [
  { slug: "ugc", name: "UGC", sort_order: 0, is_active: true },
  { slug: "pov", name: "POV", sort_order: 1, is_active: true },
  { slug: "ads", name: "Ads", sort_order: 2, is_active: true },
  { slug: "product", name: "Product", sort_order: 3, is_active: true },
  { slug: "animation", name: "Animation", sort_order: 4, is_active: true },
  { slug: "cinematic", name: "Cinematic", sort_order: 5, is_active: true },
  { slug: "talking-head", name: "Talking Head", sort_order: 6, is_active: true },
  { slug: "lifestyle", name: "Lifestyle", sort_order: 7, is_active: true },
];

export const demoModels: Model[] = [
  { slug: "seedance", name: "Seedance", sort_order: 0, is_active: true },
  { slug: "veo-3", name: "Veo 3", sort_order: 1, is_active: true },
  { slug: "sora", name: "Sora", sort_order: 2, is_active: true },
  { slug: "kling", name: "Kling", sort_order: 3, is_active: true },
  { slug: "gemini", name: "Gemini", sort_order: 4, is_active: true },
  { slug: "chatgpt", name: "ChatGPT", sort_order: 5, is_active: true },
  { slug: "nano-banana", name: "Nano Banana", sort_order: 6, is_active: true },
  { slug: "midjourney", name: "Midjourney", sort_order: 7, is_active: true },
  { slug: "runway", name: "Runway", sort_order: 8, is_active: true },
];

export const demoProfiles: Profile[] = [
  {
    id: "demo-user-1",
    username: "sarah_creates",
    display_name: "Sarah Chen",
    avatar_url: "https://images.unsplash.com/photo-1494790108755-2616b0e099d8?w=100&h=100&fit=crop&crop=face",
    bio: "AI video creator specializing in UGC ads and product demos. 4 years in digital marketing.",
    role: "creator",
    plan: "pro",
    links: { website: "https://sarahcreates.co" },
    is_banned: false,
    created_at: "2025-06-01T00:00:00Z",
  },
  {
    id: "demo-user-2",
    username: "marcus.ai",
    display_name: "Marcus Williams",
    avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face",
    bio: "Prompt engineer and AI filmmaker. Making cinematic content accessible to everyone.",
    role: "creator",
    plan: "free",
    links: null,
    is_banned: false,
    created_at: "2025-07-15T00:00:00Z",
  },
  {
    id: "demo-user-3",
    username: "pixel_luna",
    display_name: "Luna Park",
    avatar_url: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face",
    bio: "Animation and motion design. Turning brands into moving art with AI tools.",
    role: "creator",
    plan: "pro",
    links: null,
    is_banned: false,
    created_at: "2025-05-20T00:00:00Z",
  },
];

// Pexels free-to-use image URLs for demo
const pexelsImages = [
  "https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?auto=compress&cs=tinysrgb&w=600",
  "https://images.pexels.com/photos/5632399/pexels-photo-5632399.jpeg?auto=compress&cs=tinysrgb&w=600",
  "https://images.pexels.com/photos/4050315/pexels-photo-4050315.jpeg?auto=compress&cs=tinysrgb&w=600",
  "https://images.pexels.com/photos/3184298/pexels-photo-3184298.jpeg?auto=compress&cs=tinysrgb&w=600",
  "https://images.pexels.com/photos/5082579/pexels-photo-5082579.jpeg?auto=compress&cs=tinysrgb&w=600",
  "https://images.pexels.com/photos/4348401/pexels-photo-4348401.jpeg?auto=compress&cs=tinysrgb&w=600",
  "https://images.pexels.com/photos/3771836/pexels-photo-3771836.jpeg?auto=compress&cs=tinysrgb&w=600",
  "https://images.pexels.com/photos/5632381/pexels-photo-5632381.jpeg?auto=compress&cs=tinysrgb&w=600",
  "https://images.pexels.com/photos/4050291/pexels-photo-4050291.jpeg?auto=compress&cs=tinysrgb&w=600",
  "https://images.pexels.com/photos/4050344/pexels-photo-4050344.jpeg?auto=compress&cs=tinysrgb&w=600",
  "https://images.pexels.com/photos/3807517/pexels-photo-3807517.jpeg?auto=compress&cs=tinysrgb&w=600",
  "https://images.pexels.com/photos/4050334/pexels-photo-4050334.jpeg?auto=compress&cs=tinysrgb&w=600",
  "https://images.pexels.com/photos/1714208/pexels-photo-1714208.jpeg?auto=compress&cs=tinysrgb&w=600",
  "https://images.pexels.com/photos/1779487/pexels-photo-1779487.jpeg?auto=compress&cs=tinysrgb&w=600",
];

const pexelsVideos = [
  "https://videos.pexels.com/video-files/3571264/3571264-sd_640_360_30fps.mp4",
  "https://videos.pexels.com/video-files/856116/856116-sd_640_360_30fps.mp4",
  "https://videos.pexels.com/video-files/3571264/3571264-sd_640_360_30fps.mp4",
  "https://videos.pexels.com/video-files/4065924/4065924-sd_640_360_24fps.mp4",
  "https://videos.pexels.com/video-files/3571264/3571264-sd_640_360_30fps.mp4",
  "https://videos.pexels.com/video-files/856116/856116-sd_640_360_30fps.mp4",
  "https://videos.pexels.com/video-files/4434242/4434242-sd_640_360_24fps.mp4",
  "https://videos.pexels.com/video-files/3571264/3571264-sd_640_360_30fps.mp4",
  "https://videos.pexels.com/video-files/5377684/5377684-sd_640_360_25fps.mp4",
  "https://videos.pexels.com/video-files/856116/856116-sd_640_360_30fps.mp4",
];

export const demoPrompts: Prompt[] = [
  // ── Video prompts (10) ──
  {
    id: "demo-prompt-1",
    user_id: "demo-user-1",
    media_type: "video",
    media_url: pexelsVideos[0],
    thumbnail_url: pexelsImages[0],
    aspect_ratio: 9 / 16,
    duration_sec: 15,
    title: "UGC Skincare Routine — Morning Glow",
    prompt_text: "A young woman in soft morning light films herself in a bathroom mirror. She opens a small glass bottle of serum, tilts her head slightly, and pats the serum onto her cheeks with her fingertips. Camera is handheld, slightly shaky for authenticity. She looks directly at the camera, smiles warmly, and gives a slight nod. Warm, golden-hour tones, shallow depth of field on the product. No text overlays. Natural audio of fingers tapping skin.",
    negative_prompt: "blurry face, dark shadows, overexposed, text overlay, watermark",
    settings: { seed: 42, resolution: "1080x1920" },
    category_slug: "ugc",
    model_slug: "veo-3",
    tags: ["skincare", "ugc", "beauty", "routine", "morning"],
    status: "approved",
    reject_reason: null,
    is_featured: true,
    copy_count: 342,
    view_count: 1820,
    save_count: 89,
    created_at: "2025-12-01T10:00:00Z",
  },
  {
    id: "demo-prompt-2",
    user_id: "demo-user-2",
    media_type: "video",
    media_url: pexelsVideos[1],
    thumbnail_url: pexelsImages[1],
    aspect_ratio: 16 / 9,
    duration_sec: 20,
    title: "Cinematic POV — Walking Through Tokyo Neon Streets",
    prompt_text: "First-person POV walking through Shibuya at night. Rain-slicked streets reflect pink and blue neon signs. The camera bobs slightly with each step, mimicking real walking. Crowds of people pass on both sides, blurred. A subway entrance appears ahead with warm light spilling out. Film grain, anamorphic lens flares, 24fps cinematic feel. Ambient city sounds: distant chatter, car tires on wet asphalt, the hum of vending machines.",
    negative_prompt: "static camera, cartoon, overlit, no lens flares",
    settings: { seed: 1337 },
    category_slug: "pov",
    model_slug: "sora",
    tags: ["pov", "cinematic", "tokyo", "neon", "night", "rain"],
    status: "approved",
    reject_reason: null,
    is_featured: true,
    copy_count: 567,
    view_count: 3200,
    save_count: 201,
    created_at: "2025-11-28T15:00:00Z",
  },
  {
    id: "demo-prompt-3",
    user_id: "demo-user-1",
    media_type: "video",
    media_url: pexelsVideos[2],
    thumbnail_url: pexelsImages[2],
    aspect_ratio: 9 / 16,
    duration_sec: 12,
    title: "Product Ad — Premium Headphones Unboxing",
    prompt_text: "Close-up of hands lifting a matte black wireless headphone from a sleek white box. Camera tracks upward as the headphones are raised. Soft studio lighting from the left. The headband catches light with a subtle metallic sheen. Background: pure white cyclorama. Camera slowly orbits 30 degrees. No music, just the satisfying click of the hinge and the rustle of packaging.",
    negative_prompt: "busy background, low quality, pixelated, multiple products",
    settings: null,
    category_slug: "product",
    model_slug: "seedance",
    tags: ["product", "unboxing", "headphones", "premium", "ad"],
    status: "approved",
    reject_reason: null,
    is_featured: false,
    copy_count: 189,
    view_count: 920,
    save_count: 45,
    created_at: "2025-12-05T09:30:00Z",
  },
  {
    id: "demo-prompt-4",
    user_id: "demo-user-3",
    media_type: "video",
    media_url: pexelsVideos[3],
    thumbnail_url: pexelsImages[3],
    aspect_ratio: 1,
    duration_sec: 8,
    title: "3D Animation — Floating Logo Reveal",
    prompt_text: "A minimalist 3D logo made of frosted glass slowly rotates against a deep navy background. Soft caustic light patterns dance across its surface. The camera slowly dollies forward. Particles of light drift upward like fireflies. The animation is smooth, 60fps, with subtle motion blur. Premium, Apple-keynote quality feel. Ambient electronic pad in background.",
    negative_prompt: "cheap 3d, plastic look, harsh shadows, text",
    settings: { resolution: "1080x1080", duration: "8s" },
    category_slug: "animation",
    model_slug: "kling",
    tags: ["animation", "3d", "logo", "glass", "minimal"],
    status: "approved",
    reject_reason: null,
    is_featured: true,
    copy_count: 423,
    view_count: 2100,
    save_count: 156,
    created_at: "2025-12-03T14:00:00Z",
  },
  {
    id: "demo-prompt-5",
    user_id: "demo-user-2",
    media_type: "video",
    media_url: pexelsVideos[4],
    thumbnail_url: pexelsImages[4],
    aspect_ratio: 9 / 16,
    duration_sec: 18,
    title: "Talking Head — Tech Review Style",
    prompt_text: "A man in his 30s sits at a clean desk with a large monitor behind him showing code. He speaks directly to camera with enthusiastic hand gestures. Camera is eye-level, slightly wide angle. Soft ring light reflection in his eyes. He occasionally glances down at his hands as he explains. Background is a tastefully decorated home office: plants, books, warm LED strip along the monitor. Natural, conversational speaking style.",
    negative_prompt: "green screen, bad lip sync, robotic movement",
    settings: null,
    category_slug: "talking-head",
    model_slug: "veo-3",
    tags: ["talking-head", "tech", "review", "presenter", "ugc"],
    status: "approved",
    reject_reason: null,
    is_featured: false,
    copy_count: 98,
    view_count: 540,
    save_count: 32,
    created_at: "2025-12-04T11:00:00Z",
  },
  {
    id: "demo-prompt-6",
    user_id: "demo-user-1",
    media_type: "video",
    media_url: pexelsVideos[5],
    thumbnail_url: pexelsImages[5],
    aspect_ratio: 9 / 16,
    duration_sec: 10,
    title: "UGC Ad — Coffee Brand Lifestyle",
    prompt_text: "A woman sits in a sunlit cafe window seat, wrapping both hands around a ceramic cup of latte with visible latte art. She inhales deeply, eyes closed, then takes a slow sip and smiles contentedly. Shot on a long lens with creamy bokeh of other cafe patrons behind. Warm tones, film-like color grading. Sound: quiet cafe ambiance, the clink of the cup against the saucer.",
    negative_prompt: "harsh lighting, shaky cam, fast cuts, branded logos visible",
    settings: { seed: 88 },
    category_slug: "ugc",
    model_slug: "nano-banana",
    tags: ["ugc", "coffee", "lifestyle", "cafe", "ad"],
    status: "approved",
    reject_reason: null,
    is_featured: false,
    copy_count: 156,
    view_count: 780,
    save_count: 67,
    created_at: "2025-12-06T08:00:00Z",
  },
  {
    id: "demo-prompt-7",
    user_id: "demo-user-3",
    media_type: "video",
    media_url: pexelsVideos[6],
    thumbnail_url: pexelsImages[6],
    aspect_ratio: 16 / 9,
    duration_sec: 25,
    title: "Cinematic — Drone Sunrise Over Mountain Lake",
    prompt_text: "Aerial drone shot at dawn, slowly flying forward over a perfectly still mountain lake. The water mirrors the sky perfectly. Snow-capped peaks in the distance are lit pink and gold by the rising sun. Camera tilts down slightly to reveal a single wooden canoe floating near the shore. Mist hugs the water surface. 4K, no color correction needed — the raw beauty should speak for itself. Ambient sound: birds, gentle water lapping.",
    negative_prompt: "sunset instead of sunrise, busy scene, boats, people, text",
    settings: null,
    category_slug: "cinematic",
    model_slug: "runway",
    tags: ["cinematic", "drone", "landscape", "sunrise", "mountain", "lake"],
    status: "approved",
    reject_reason: null,
    is_featured: true,
    copy_count: 678,
    view_count: 4100,
    save_count: 289,
    created_at: "2025-11-25T06:00:00Z",
  },
  {
    id: "demo-prompt-8",
    user_id: "demo-user-2",
    media_type: "video",
    media_url: pexelsVideos[7],
    thumbnail_url: pexelsImages[7],
    aspect_ratio: 9 / 16,
    duration_sec: 14,
    title: "Food Ad — Slow Motion Chocolate Pour",
    prompt_text: "Extreme close-up of dark chocolate being poured in slow motion over a stack of fresh strawberries on a marble surface. The chocolate cascades smoothly, creating perfect drips and rivulets. Camera dollies slowly to the right. Shallow depth of field with the front strawberry sharp. Studio lighting from above and behind creates a rim light on the chocolate stream. Speed: 120fps rendered at 24fps.",
    negative_prompt: "messy background, multiple foods, hands visible, fast motion",
    settings: { resolution: "1080x1920" },
    category_slug: "ads",
    model_slug: "gemini",
    tags: ["food", "chocolate", "slowmo", "ad", "product"],
    status: "approved",
    reject_reason: null,
    is_featured: false,
    copy_count: 245,
    view_count: 1350,
    save_count: 112,
    created_at: "2025-12-02T16:00:00Z",
  },
  {
    id: "demo-prompt-9",
    user_id: "demo-user-1",
    media_type: "video",
    media_url: pexelsVideos[8],
    thumbnail_url: pexelsImages[8],
    aspect_ratio: 9 / 16,
    duration_sec: 15,
    title: "POV — Morning Routine Desk Setup",
    prompt_text: "First-person view of hands arranging a minimal desk setup. The hands place a MacBook on a wooden desk, align a wireless keyboard and mouse, then set a small plant in the corner. A cup of coffee is placed to the right. Morning light streams through a window on the left, casting soft shadows. Each item is placed with deliberate, satisfying precision. ASMR-quality sounds of objects being set down on wood.",
    negative_prompt: "cluttered desk, dark room, fast movement, multiple people",
    settings: null,
    category_slug: "pov",
    model_slug: "chatgpt",
    tags: ["pov", "desk", "setup", "minimal", "asmr", "routine"],
    status: "approved",
    reject_reason: null,
    is_featured: false,
    copy_count: 134,
    view_count: 720,
    save_count: 56,
    created_at: "2025-12-07T07:00:00Z",
  },
  {
    id: "demo-prompt-10",
    user_id: "demo-user-3",
    media_type: "video",
    media_url: pexelsVideos[9],
    thumbnail_url: pexelsImages[9],
    aspect_ratio: 16 / 9,
    duration_sec: 30,
    title: "Lifestyle — Golden Hour Rooftop Party",
    prompt_text: "Wide establishing shot of a rooftop party at golden hour in a coastal city. String lights crisscross above. A small group of friends (mid-20s, diverse) clink glasses, laughing naturally. Camera slowly moves through the scene at waist height, weaving between guests. The ocean is visible in the background with the sun low on the horizon. Color palette: warm golds, soft oranges, deep turquoise sky. Film grain, slightly desaturated shadows. Music: lo-fi house faintly in background.",
    negative_prompt: "indoor scene, dark, crowded nightclub, strobe lights",
    settings: null,
    category_slug: "lifestyle",
    model_slug: "sora",
    tags: ["lifestyle", "party", "rooftop", "golden-hour", "friends"],
    status: "approved",
    reject_reason: null,
    is_featured: false,
    copy_count: 89,
    view_count: 480,
    save_count: 34,
    created_at: "2025-12-08T17:00:00Z",
  },
  // ── Image prompts (14) ──
  {
    id: "demo-prompt-11",
    user_id: "demo-user-1",
    media_type: "image",
    media_url: pexelsImages[0],
    thumbnail_url: null,
    aspect_ratio: 1,
    duration_sec: null,
    title: "Product Shot — Minimal Perfume Bottle",
    prompt_text: "A frosted glass perfume bottle with a gold cap, centered on a smooth marble surface. Soft, diffused studio lighting from the upper left. A single orchid petal lies next to the bottle. Background: seamless warm gray gradient. The bottle casts a subtle, sharp shadow. Photorealistic, 85mm lens, f/2.8. No text, no branding. Luxury editorial feel.",
    negative_prompt: "busy background, multiple products, text, watermark",
    settings: null,
    category_slug: "product",
    model_slug: "midjourney",
    tags: ["product", "perfume", "minimal", "luxury", "editorial"],
    status: "approved",
    reject_reason: null,
    is_featured: true,
    copy_count: 512,
    view_count: 2800,
    save_count: 178,
    created_at: "2025-12-01T12:00:00Z",
  },
  {
    id: "demo-prompt-12",
    user_id: "demo-user-2",
    media_type: "image",
    media_url: pexelsImages[1],
    thumbnail_url: null,
    aspect_ratio: 3 / 4,
    duration_sec: null,
    title: "Cinematic Still — Rainy Window Portrait",
    prompt_text: "Close-up portrait of a person looking out a rain-streaked window. Their face is partially reflected in the glass. Moody blue-green color grading. Shallow depth of field, with the rain drops on the glass in sharp focus and the face softly blurred. Natural daylight from outside illuminates the scene. Film grain, Kodak Portra 400 emulation. Emotion: contemplative, melancholic.",
    negative_prompt: "bright sunny day, smiling, multiple people, outdoor scene",
    settings: null,
    category_slug: "cinematic",
    model_slug: "chatgpt",
    tags: ["portrait", "cinematic", "rain", "moody", "film"],
    status: "approved",
    reject_reason: null,
    is_featured: false,
    copy_count: 234,
    view_count: 1200,
    save_count: 89,
    created_at: "2025-12-02T10:00:00Z",
  },
  {
    id: "demo-prompt-13",
    user_id: "demo-user-3",
    media_type: "image",
    media_url: pexelsImages[2],
    thumbnail_url: null,
    aspect_ratio: 1,
    duration_sec: null,
    title: "Flat Lay — Coffee & Planner Aesthetic",
    prompt_text: "Overhead flat lay shot on a linen tablecloth: an open leather planner with handwritten notes, a cup of black coffee with steam rising, a mechanical pencil, a small succulent in a terra cotta pot, and a pair of reading glasses. Everything arranged with intentional whitespace. Soft, even natural light from a north-facing window. Color palette: warm neutrals, cream, tan, dark green. Shot on Phase One IQ4, tethered.",
    negative_prompt: "cluttered, colorful items, digital devices, brand logos",
    settings: null,
    category_slug: "lifestyle",
    model_slug: "midjourney",
    tags: ["flatlay", "coffee", "planner", "aesthetic", "minimal"],
    status: "approved",
    reject_reason: null,
    is_featured: false,
    copy_count: 178,
    view_count: 940,
    save_count: 67,
    created_at: "2025-12-03T09:00:00Z",
  },
  {
    id: "demo-prompt-14",
    user_id: "demo-user-1",
    media_type: "image",
    media_url: pexelsImages[3],
    thumbnail_url: null,
    aspect_ratio: 16 / 9,
    duration_sec: null,
    title: "Ad Creative — SaaS Dashboard Preview",
    prompt_text: "A clean, modern SaaS dashboard mockup displayed on a MacBook Pro placed on a minimal white desk. The dashboard shows analytics charts with a green-and-white color scheme. Soft ambient lighting, slight depth of field on the keyboard. A small plant and a coffee cup are partially visible at the edges. The screen content should be clearly readable but fictitious. No real company logos.",
    negative_prompt: "dark mode, gaming setup, multiple monitors, messy desk",
    settings: null,
    category_slug: "ads",
    model_slug: "gemini",
    tags: ["saas", "dashboard", "mockup", "tech", "ad"],
    status: "approved",
    reject_reason: null,
    is_featured: false,
    copy_count: 312,
    view_count: 1650,
    save_count: 143,
    created_at: "2025-12-04T14:00:00Z",
  },
  {
    id: "demo-prompt-15",
    user_id: "demo-user-2",
    media_type: "image",
    media_url: pexelsImages[4],
    thumbnail_url: null,
    aspect_ratio: 9 / 16,
    duration_sec: null,
    title: "UGC Selfie — Gym Progress Shot",
    prompt_text: "A fitness influencer takes a mirror selfie in a well-lit modern gym. They're wearing minimal athletic wear and holding their phone at chest height. Natural, unposed stance — one hand on hip, slight smile. The gym is clean with modern equipment blurred in the background. Warm, slightly desaturated color grading. Shot appears captured on iPhone with Portrait mode (natural bokeh). No filters, no heavy editing.",
    negative_prompt: "professional studio, posing dramatically, dark gym, dirty mirror",
    settings: null,
    category_slug: "ugc",
    model_slug: "chatgpt",
    tags: ["ugc", "fitness", "selfie", "gym", "influencer"],
    status: "approved",
    reject_reason: null,
    is_featured: false,
    copy_count: 156,
    view_count: 820,
    save_count: 45,
    created_at: "2025-12-05T16:00:00Z",
  },
  {
    id: "demo-prompt-16",
    user_id: "demo-user-3",
    media_type: "image",
    media_url: pexelsImages[5],
    thumbnail_url: null,
    aspect_ratio: 1,
    duration_sec: null,
    title: "3D Render — Glass Morphism App Icon",
    prompt_text: "A 3D rendered app icon floating at a slight angle on a soft gradient background (light lavender to soft peach). The icon is a rounded square with frosted glass material, showing subtle refraction and caustics. Inside the glass: a simple geometric AI brain symbol in white. Soft shadow beneath. Clean, Apple-design-system aesthetic. Octane render quality, 4K.",
    negative_prompt: "flat design, dark background, complex icon, text inside icon",
    settings: null,
    category_slug: "animation",
    model_slug: "midjourney",
    tags: ["3d", "icon", "glass", "app", "design", "render"],
    status: "approved",
    reject_reason: null,
    is_featured: true,
    copy_count: 445,
    view_count: 2300,
    save_count: 189,
    created_at: "2025-12-01T18:00:00Z",
  },
  {
    id: "demo-prompt-17",
    user_id: "demo-user-1",
    media_type: "image",
    media_url: pexelsImages[6],
    thumbnail_url: null,
    aspect_ratio: 3 / 2,
    duration_sec: null,
    title: "Food Photography — Rustic Bread Baking",
    prompt_text: "A freshly baked sourdough loaf on a wooden cutting board, sliced to reveal the open crumb structure. Flour dust floats in a beam of sunlight from a side window. Background: a rustic kitchen with copper pots slightly out of focus. A linen towel and a vintage bread knife complete the scene. Shot at f/4, 50mm, with rich warm tones. Food styling is imperfect and authentic — this is homemade, not commercial.",
    negative_prompt: "commercial bakery, plastic wrap, perfect slices, cold lighting",
    settings: null,
    category_slug: "lifestyle",
    model_slug: "gemini",
    tags: ["food", "bread", "baking", "rustic", "photography"],
    status: "approved",
    reject_reason: null,
    is_featured: false,
    copy_count: 201,
    view_count: 1050,
    save_count: 78,
    created_at: "2025-12-06T13:00:00Z",
  },
  {
    id: "demo-prompt-18",
    user_id: "demo-user-2",
    media_type: "image",
    media_url: pexelsImages[7],
    thumbnail_url: null,
    aspect_ratio: 4 / 5,
    duration_sec: null,
    title: "Fashion — Editorial Street Style",
    prompt_text: "Full-body fashion photograph of a model walking on an empty cobblestone street in early morning. They wear an oversized camel trench coat, white sneakers, and carry a small leather crossbody bag. Wind slightly catches the coat hem. Building facades in muted pastels provide the backdrop. Shot on medium format with shallow depth of field. Color grading: desaturated, with lifted blacks and warm highlights. Fashion editorial, not commercial catalog.",
    negative_prompt: "studio background, heavy makeup, posed stiffly, HDR look",
    settings: null,
    category_slug: "lifestyle",
    model_slug: "midjourney",
    tags: ["fashion", "editorial", "street", "style", "model"],
    status: "approved",
    reject_reason: null,
    is_featured: false,
    copy_count: 289,
    view_count: 1480,
    save_count: 134,
    created_at: "2025-12-07T11:00:00Z",
  },
  {
    id: "demo-prompt-19",
    user_id: "demo-user-3",
    media_type: "image",
    media_url: pexelsImages[8],
    thumbnail_url: null,
    aspect_ratio: 16 / 9,
    duration_sec: null,
    title: "Product — Wireless Earbuds on Marble",
    prompt_text: "A pair of matte black wireless earbuds resting in their open charging case on a white marble surface. Shot from a 45-degree angle. Soft directional light from the right creates gentle shadows. One earbud is slightly lifted as if about to be picked up. Reflection visible on the marble. Clean, Apple-product-photography style. Background: pure white. 100mm macro lens, f/5.6.",
    negative_prompt: "colored background, busy scene, wires, other electronics",
    settings: null,
    category_slug: "product",
    model_slug: "chatgpt",
    tags: ["product", "earbuds", "tech", "minimal", "macro"],
    status: "approved",
    reject_reason: null,
    is_featured: false,
    copy_count: 167,
    view_count: 890,
    save_count: 56,
    created_at: "2025-12-08T10:00:00Z",
  },
  {
    id: "demo-prompt-20",
    user_id: "demo-user-1",
    media_type: "image",
    media_url: pexelsImages[9],
    thumbnail_url: null,
    aspect_ratio: 1,
    duration_sec: null,
    title: "Illustration — Cozy Reading Nook",
    prompt_text: "Digital illustration of a cozy window seat reading nook. Tall bookshelves frame a window showing a rainy autumn scene outside. A cat curls up on a pile of cushions next to an open book and a steaming mug. Warm lamp light contrasts with the cool blue rain outside. Style: detailed gouache illustration with visible texture. Muted, warm color palette with pops of orange and forest green. Storybook quality.",
    negative_prompt: "photorealistic, harsh lines, neon colors, anime style",
    settings: null,
    category_slug: "animation",
    model_slug: "midjourney",
    tags: ["illustration", "cozy", "reading", "cat", "autumn"],
    status: "approved",
    reject_reason: null,
    is_featured: false,
    copy_count: 345,
    view_count: 1800,
    save_count: 234,
    created_at: "2025-12-03T15:00:00Z",
  },
  {
    id: "demo-prompt-21",
    user_id: "demo-user-2",
    media_type: "image",
    media_url: pexelsImages[10],
    thumbnail_url: null,
    aspect_ratio: 9 / 16,
    duration_sec: null,
    title: "Ad Creative — Fitness App Hero",
    prompt_text: "A hero image for a fitness tracking app. A person mid-stride on a mountain trail at sunrise, shot from behind. They wear minimal running gear. The trail curves into the distance with dramatic lighting — warm golden rays piercing through mountain fog. Overlay-friendly: the right third is slightly darker and emptier for text placement. Aspirational, energetic, premium feel.",
    negative_prompt: "gym interior, group class, flat lighting, text already present",
    settings: null,
    category_slug: "ads",
    model_slug: "veo-3",
    tags: ["ad", "fitness", "app", "hero", "trail", "sunrise"],
    status: "approved",
    reject_reason: null,
    is_featured: false,
    copy_count: 198,
    view_count: 1040,
    save_count: 87,
    created_at: "2025-12-04T07:00:00Z",
  },
  {
    id: "demo-prompt-22",
    user_id: "demo-user-3",
    media_type: "image",
    media_url: pexelsImages[11],
    thumbnail_url: null,
    aspect_ratio: 1,
    duration_sec: null,
    title: "Architecture — Brutalist Stairwell",
    prompt_text: "Looking straight up inside a brutalist concrete spiral stairwell. The stairs wrap in a tight helix with sharp geometric shadows. A single beam of warm sunlight enters from a small window at the top, creating a bright focal point. Everything else is cool gray concrete with visible form marks. Shot on ultra-wide lens, 14mm equivalent. High contrast black and white with one warm-toned sunbeam. Architectural photography, minimalist composition.",
    negative_prompt: "people in frame, modern glass building, colored walls, handrails",
    settings: null,
    category_slug: "cinematic",
    model_slug: "seedance",
    tags: ["architecture", "brutalist", "concrete", "minimal", "geometric"],
    status: "approved",
    reject_reason: null,
    is_featured: false,
    copy_count: 234,
    view_count: 1200,
    save_count: 98,
    created_at: "2025-12-05T12:00:00Z",
  },
  {
    id: "demo-prompt-23",
    user_id: "demo-user-1",
    media_type: "image",
    media_url: pexelsImages[12],
    thumbnail_url: null,
    aspect_ratio: 4 / 3,
    duration_sec: null,
    title: "Talking Head Thumbnail — Podcast Cover",
    prompt_text: "A professional podcast cover photo: a person sitting in a well-designed home studio with acoustic panels and warm LED lighting behind them. They lean forward slightly toward a microphone, making eye contact with the camera. Expression: engaged, mid-thought. Shot at f/2.0 with beautiful bokeh on the studio equipment behind. Color grading: warm, slightly moody with teal shadows and orange highlights. Clean, thumbnail-optimized composition with the subject off-center left.",
    negative_prompt: "messy room, harsh overhead lighting, looking away, too dark",
    settings: null,
    category_slug: "talking-head",
    model_slug: "nano-banana",
    tags: ["podcast", "thumbnail", "portrait", "studio", "creator"],
    status: "approved",
    reject_reason: null,
    is_featured: false,
    copy_count: 145,
    view_count: 760,
    save_count: 42,
    created_at: "2025-12-06T16:00:00Z",
  },
  {
    id: "demo-prompt-24",
    user_id: "demo-user-2",
    media_type: "image",
    media_url: pexelsImages[13],
    thumbnail_url: null,
    aspect_ratio: 16 / 9,
    duration_sec: null,
    title: "Abstract — AI Neural Network Visualization",
    prompt_text: "Abstract visualization of a neural network as a field of interconnected glowing nodes. Nodes are small spheres of varying sizes connected by thin luminous threads. Color palette: deep space blue background with nodes in warm white, soft gold, and pale cyan. The network forms a gentle wave pattern across the frame. Depth of field creates a tilt-shift miniature effect. No text, no UI elements — pure abstract data art. 8K resolution, subtle film grain.",
    negative_prompt: "matrix green, circuit board, brain shape, text labels, UI elements",
    settings: null,
    category_slug: "animation",
    model_slug: "gemini",
    tags: ["abstract", "neural", "network", "ai", "visualization", "data"],
    status: "approved",
    reject_reason: null,
    is_featured: true,
    copy_count: 389,
    view_count: 2050,
    save_count: 167,
    created_at: "2025-12-02T20:00:00Z",
  },
];
